name: "Check for license list version"
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check license list version
      run: |
        remote=$(curl https://spdx.org/licenses/ | grep 'licenseListVersion' | grep -Po '[0-9]{4}-[0-9]{2}-[0-9]{2}')
        local=$(grep -Po '[0-9]{4}-[0-9]{2}-[0-9]{2}' spdx.el)
        if [[ "$remote" != "$local" ]]; then
          exit -1
        fi
